# Generated by Django 5.0.3 on 2024-03-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_article_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
