# Generated by Django 5.0.3 on 2024-03-18 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_sum',
        ),
    ]
