# Generated by Django 5.0.3 on 2024-03-18 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_cart_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='sum_orders',
        ),
    ]
