# Generated by Django 5.0.3 on 2024-03-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_rename_total_price_order_sum_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
