# Generated by Django 5.0.3 on 2024-03-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_article_image_url_article_paragraph'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='paragraph',
            new_name='in_string_img',
        ),
    ]
