# Generated by Django 5.0.3 on 2024-03-19 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_rename_paragraph_article_in_string_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='in_string_img',
        ),
    ]
