# Generated by Django 5.0.3 on 2024-03-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
