# Generated by Django 5.0.3 on 2024-03-25 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_alter_order_product_alter_order_sum_orders_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sum_orders',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sum_orders', to='mainapp.product'),
        ),
    ]
