# Generated by Django 5.0.3 on 2024-03-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_remove_order_sum_orders_alter_order_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
