# Generated by Django 5.0.3 on 2024-03-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_user_first_name_user_patronymic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postal_сode',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
