# Generated by Django 5.0.3 on 2024-03-26 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_category_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
