# Generated by Django 4.2.11 on 2024-04-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_remove_cart_products_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_items',
            field=models.ManyToManyField(related_name='carts', to='mainapp.cartitem'),
        ),
    ]
