# Generated by Django 4.2.11 on 2024-04-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_remove_cart_cart_items_alter_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
    ]
