# Generated by Django 4.2.11 on 2024-04-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_rename_category_product_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stl_file',
            field=models.FileField(default=0, upload_to='stl_files/'),
            preserve_default=False,
        ),
    ]
